#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "07f8fe12acba46bbba773dbf6b68aa81"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "f591d1c7-0060-4d35-a146-099ec27b49b1"
preview_database_id = "f591d1c7-0060-4d35-a146-099ec27b49b1"
migrations_dir = "app/drizzle"
